package kval;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.cell.PropertyValueFactory;

import java.net.URL;
import java.util.List;
import java.util.ResourceBundle;

import org.springframework.jdbc.core.JdbcTemplate;

import com.mysql.cj.jdbc.MysqlDataSource;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;

public class MainWinController implements Initializable {
	
	MysqlDataSource dataSource = new MysqlDataSource();
	JdbcTemplate jdbc;
	RequestDao requestDao = new RequestDao(dataSource);
	ObservableList<Request> requestList = FXCollections.observableArrayList();
	
	@FXML
	private TableView<Request> ApplicationTable;
	@FXML
	private TableColumn<Request, Integer> ColIdRequest;
	@FXML
	private TableColumn<Request, String> ColAddDate;
	@FXML
	private TableColumn<Request, String> ColComments;
	@FXML
	private TableColumn<Request, String> ColStatus;
	@FXML
	private TableColumn<Request, Integer> ColIdTech;
	@FXML
	private TableColumn<Request, Integer> ColIdClient;
	@FXML
	private TextField AddDateField;
	@FXML
	private TextField CommentsField;
	@FXML
	private Button AddBtn;
	@FXML
	private Button EditBtn;
	@FXML
	private TextField IdTechField;
	@FXML
	private TextField StatusField;
	@FXML
	private TextField IdRequestField;
	@FXML
	private TextField IdClientField;

	// Event Listener on Button[#AddBtn].onAction
	@FXML
	public void add_appl(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#EditBtn].onAction
	@FXML
	public void change_appl(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		ApplicationTable.getItems().clear();
	    dataSource.setServerName("localhost");
	    dataSource.setPort(3306);
	    dataSource.setDatabaseName("TechRepair");
	    dataSource.setUser("root");
	    dataSource.setPassword("");
	    
	    jdbc = new JdbcTemplate(dataSource);
		
		ColIdRequest.setCellValueFactory(new PropertyValueFactory<Request, Integer>("id_request"));
        ColAddDate.setCellValueFactory(new PropertyValueFactory<Request, String>("add_date"));
        ColComments.setCellValueFactory(new PropertyValueFactory<Request, String>("comments"));
        ColStatus.setCellValueFactory(new PropertyValueFactory<Request, String>("status"));
        ColIdTech.setCellValueFactory(new PropertyValueFactory<Request, Integer>("idtech"));
        ColIdClient.setCellValueFactory(new PropertyValueFactory<Request, Integer>("idclient"));

		
		RequestDao requestDao = new RequestDao(dataSource);
		requestList.addAll(requestDao.getAll());
	    ApplicationTable.setItems(requestList);
	}
}
